### ISSUE TITLE
Visualize AIGER files 

### ISSUE THREAD

**Issue by wonhyukchoi** [JKomp/AIGER#2]
Hi, any possibility to support visualizations of AIGER files, like [`aigtodot`](http://fmv.jku.at/aiger/)?

**Comment by JKomp** [comment]
Does the -d option not generate the map you're looking for?

**Comment by wonhyukchoi** [comment]
It does, but currently doing so seems to require the stimulation file.

Is it possible to print out the AIGER file without a simulation input?

**Comment by JKomp** [comment]
I'd not really thought about it as I would just run aigtodot when I needed the original network diagram. The goal of my version of AIGER was to see how well the network could be identified through application of stimuli - kind of like the puzzle where one shoots a laser into a box of mirrors.

I could see an extension that can print the original network like aigtodot and one that prints the diff between what was actually visited and the original. If I get time in the next couple of weeks, I'll take a look at it.

**Comment by wonhyukchoi** [comment]
Thank you, appreciated.

**Comment by JKomp** [comment]
Finally added the ability to generate the original graph like aigtodot. There may be some minor differences.
